/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculo;

/**
 *
 * @author Wagner Morel
 */
public class Calculadora extends javax.swing.JFrame {

   private String valor;
   private boolean  igual, inicio = true, operacao1, operacao2;
   private double mem = 0, valor1, valor2, resultado;
   private String tipoOperacao;
           
   public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCalculadora = new javax.swing.JLabel();
        txtDisplay = new javax.swing.JTextField();
        jbUm = new javax.swing.JButton();
        jbDois = new javax.swing.JButton();
        jbTres = new javax.swing.JButton();
        jbQuatro = new javax.swing.JButton();
        jbCinco = new javax.swing.JButton();
        jbSeis = new javax.swing.JButton();
        jbSete = new javax.swing.JButton();
        jbOito = new javax.swing.JButton();
        jbNove = new javax.swing.JButton();
        jbDivisao = new javax.swing.JButton();
        jbMultiplicação = new javax.swing.JButton();
        jbSubtração = new javax.swing.JButton();
        jbPonto = new javax.swing.JButton();
        jbIgualdade = new javax.swing.JButton();
        jbAdição = new javax.swing.JButton();
        jbZero = new javax.swing.JButton();
        txtPrevio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCalculadora.setText("Calculadora");

        txtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDisplayActionPerformed(evt);
            }
        });

        jbUm.setText("1");
        jbUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbUmMouseClicked(evt);
            }
        });
        jbUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUmActionPerformed(evt);
            }
        });

        jbDois.setText("2");
        jbDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDoisMouseClicked(evt);
            }
        });
        jbDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDoisActionPerformed(evt);
            }
        });

        jbTres.setText("3");
        jbTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbTresMouseClicked(evt);
            }
        });
        jbTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTresActionPerformed(evt);
            }
        });

        jbQuatro.setText("4");
        jbQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbQuatroMouseClicked(evt);
            }
        });
        jbQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuatroActionPerformed(evt);
            }
        });

        jbCinco.setText("5");
        jbCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCincoMouseClicked(evt);
            }
        });
        jbCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCincoActionPerformed(evt);
            }
        });

        jbSeis.setText("6");
        jbSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSeisMouseClicked(evt);
            }
        });
        jbSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeisActionPerformed(evt);
            }
        });

        jbSete.setText("7");
        jbSete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSeteMouseClicked(evt);
            }
        });
        jbSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeteActionPerformed(evt);
            }
        });

        jbOito.setText("8");
        jbOito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbOitoMouseClicked(evt);
            }
        });
        jbOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOitoActionPerformed(evt);
            }
        });

        jbNove.setText("9");
        jbNove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNoveMouseClicked(evt);
            }
        });
        jbNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNoveActionPerformed(evt);
            }
        });

        jbDivisao.setText("/");
        jbDivisao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDivisaoMouseClicked(evt);
            }
        });
        jbDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivisaoActionPerformed(evt);
            }
        });

        jbMultiplicação.setText("*");
        jbMultiplicação.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbMultiplicaçãoMouseClicked(evt);
            }
        });
        jbMultiplicação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMultiplicaçãoActionPerformed(evt);
            }
        });

        jbSubtração.setText("-");
        jbSubtração.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSubtraçãoMouseClicked(evt);
            }
        });
        jbSubtração.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubtraçãoActionPerformed(evt);
            }
        });

        jbPonto.setText(".");
        jbPonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbPontoMouseClicked(evt);
            }
        });
        jbPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPontoActionPerformed(evt);
            }
        });

        jbIgualdade.setText("=");
        jbIgualdade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbIgualdadeMouseClicked(evt);
            }
        });
        jbIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIgualdadeActionPerformed(evt);
            }
        });

        jbAdição.setText("+");
        jbAdição.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAdiçãoMouseClicked(evt);
            }
        });
        jbAdição.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdiçãoActionPerformed(evt);
            }
        });

        jbZero.setText("0");
        jbZero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbZeroMouseClicked(evt);
            }
        });
        jbZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbZeroActionPerformed(evt);
            }
        });

        txtPrevio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrevioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbZero, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbIgualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbUm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbDois, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbTres, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbSete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbOito, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbNove, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbMultiplicação, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbSubtração, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbAdição, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtPrevio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCalculadora, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrevio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(txtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbOito, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbNove, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMultiplicação, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbUm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDois, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbTres, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSubtração, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbZero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbIgualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAdição, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeisActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("6");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"6");
        }
    }//GEN-LAST:event_jbSeisActionPerformed

    private void jbTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTresActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("3");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"3");
        }
    }//GEN-LAST:event_jbTresActionPerformed

    private void jbOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOitoActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("8");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"8");
        }
    }//GEN-LAST:event_jbOitoActionPerformed

    private void jbQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuatroActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("4");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"4");
        }
    }//GEN-LAST:event_jbQuatroActionPerformed

    private void jbDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivisaoActionPerformed
        igual = true;
        inicio = true;
        
        if(operacao1 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "/");
            operacao1 = false;
        }else{
            igual = true;
        inicio = true;
        
        if(operacao2 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "/");
            operacao2 = false;
        }else{
            txtPrevio.setText(txtDisplay.getText()+ "/");
            Operacoes(resultado, valor2);
           
        }
            
        }
         tipoOperacao = "/";
    }//GEN-LAST:event_jbDivisaoActionPerformed

    private void jbNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNoveActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("9");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"9");
        }
    }//GEN-LAST:event_jbNoveActionPerformed

    private void jbZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbZeroActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("0");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"0");
        }
    }//GEN-LAST:event_jbZeroActionPerformed

    private void txtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDisplayActionPerformed

    private void jbSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeteActionPerformed
        if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("7");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"7");
        }
    }//GEN-LAST:event_jbSeteActionPerformed

    private void jbSubtraçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubtraçãoActionPerformed
        igual = true;
        inicio = true;
        
        if(operacao1 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "-");
            operacao1 = false;
        }else{
            igual = true;
        inicio = true;
        
        if(operacao2 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "-");
            operacao2 = false;
        }else{
            txtPrevio.setText(txtDisplay.getText()+ "-");
            Operacoes(resultado, valor2);
           
        }
            
        }
         tipoOperacao =  "-";
    }//GEN-LAST:event_jbSubtraçãoActionPerformed

    private void jbPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPontoActionPerformed
        if (txtDisplay.getText().contains(".")){
       }else{
          txtDisplay.setText(txtDisplay.getText()+"."); 
          inicio = false;
        }
    }//GEN-LAST:event_jbPontoActionPerformed

    private void Operacoes(double valor1 , double valor2){
        
        switch(tipoOperacao){
            
        case "+":
            resultado = valor1 + valor2;
            txtDisplay.setText(resultado + "");
            valor1 = Double.parseDouble(txtDisplay.getText());
            break;
            
       case "-":
            resultado = valor1 - valor2;
            txtDisplay.setText(resultado + "");
            valor1 = Double.parseDouble(txtDisplay.getText());
            break;
            
       case "*":
            resultado = valor1 * valor2;
            txtDisplay.setText(resultado + "");
            valor1 = Double.parseDouble(txtDisplay.getText());
            break;
            
        case "/":
            if(valor2 == 0){
            txtDisplay.setText("Erro");
            break;
            
            }else{
            
            resultado = valor1 / valor2;
            txtDisplay.setText(resultado + "");
            valor1 = Double.parseDouble(txtDisplay.getText());
            break;

            }
     
            
                 
        }
            

}
    
    private void jbIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIgualdadeActionPerformed
       inicio = true;
       operacao1 = true;
       if(igual = true){
           if(tipoOperacao == null){
           
           }else{
           valor2 = Double.parseDouble(txtDisplay.getText());
           txtPrevio.setText( txtPrevio.getText() + txtDisplay.getText());
           Operacoes(valor1, valor2);
           igual = false;
           
           }
       
       }else {
            txtPrevio.setText("");
            Operacoes(valor1, valor2);      
                   
             
                   }
    }//GEN-LAST:event_jbIgualdadeActionPerformed

    private void jbAdiçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdiçãoActionPerformed
        igual = true;
        inicio = true;
        
        if(operacao1 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "+");
            operacao1 = false;
        }else{
            igual = true;
        inicio = true;
        
        if(operacao2 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "+");
            operacao2 = false;
        }else{
            txtPrevio.setText(txtDisplay.getText()+ "+");
            Operacoes(resultado, valor2);
           
        }
            
        }
         tipoOperacao = "+";
    }//GEN-LAST:event_jbAdiçãoActionPerformed

    private void jbCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCincoActionPerformed
       if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("5");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"5");
        }
    }//GEN-LAST:event_jbCincoActionPerformed

    private void jbUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUmActionPerformed
       if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("1");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"1");
        }
    }//GEN-LAST:event_jbUmActionPerformed

    private void jbDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDoisActionPerformed
 if (inicio = true){
            txtDisplay.setText("");
            txtDisplay.setText("2");
            inicio = false;
        }else {
            
            txtDisplay.setText(txtDisplay.getText()+"2");
        }
    }//GEN-LAST:event_jbDoisActionPerformed

    private void jbMultiplicaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMultiplicaçãoActionPerformed
       igual = true;
        inicio = true;
        
        if(operacao1 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "*");
            operacao1 = false;
        }else{
            igual = true;
        inicio = true;
        
        if(operacao2 = true){
            valor1 = Double.parseDouble(txtDisplay.getText());
            txtPrevio.setText("");
            txtPrevio.setText(txtDisplay.getText()+ "*");
            operacao2 = false;
        }else{
            txtPrevio.setText(txtDisplay.getText()+ "*");
            Operacoes(resultado, valor2);
           
        }
            
        }
         tipoOperacao = "*";
    }//GEN-LAST:event_jbMultiplicaçãoActionPerformed

    private void jbSeteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSeteMouseClicked
        
    }//GEN-LAST:event_jbSeteMouseClicked

    private void jbOitoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbOitoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbOitoMouseClicked

    private void jbNoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNoveMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbNoveMouseClicked

    private void jbQuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbQuatroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbQuatroMouseClicked

    private void jbCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCincoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbCincoMouseClicked

    private void jbSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSeisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSeisMouseClicked

    private void jbUmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbUmMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbUmMouseClicked

    private void jbDoisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDoisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDoisMouseClicked

    private void jbTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbTresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTresMouseClicked

    private void jbZeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbZeroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbZeroMouseClicked

    private void jbPontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbPontoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbPontoMouseClicked

    private void jbIgualdadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbIgualdadeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbIgualdadeMouseClicked

    private void jbDivisaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDivisaoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbDivisaoMouseClicked

    private void jbMultiplicaçãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbMultiplicaçãoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMultiplicaçãoMouseClicked

    private void jbSubtraçãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSubtraçãoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbSubtraçãoMouseClicked

    private void jbAdiçãoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAdiçãoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAdiçãoMouseClicked

    private void txtPrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrevioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrevioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdição;
    private javax.swing.JButton jbCinco;
    private javax.swing.JButton jbDivisao;
    private javax.swing.JButton jbDois;
    private javax.swing.JButton jbIgualdade;
    private javax.swing.JButton jbMultiplicação;
    private javax.swing.JButton jbNove;
    private javax.swing.JButton jbOito;
    private javax.swing.JButton jbPonto;
    private javax.swing.JButton jbQuatro;
    private javax.swing.JButton jbSeis;
    private javax.swing.JButton jbSete;
    private javax.swing.JButton jbSubtração;
    private javax.swing.JButton jbTres;
    private javax.swing.JButton jbUm;
    private javax.swing.JButton jbZero;
    private javax.swing.JLabel lblCalculadora;
    private javax.swing.JTextField txtDisplay;
    private javax.swing.JTextField txtPrevio;
    // End of variables declaration//GEN-END:variables
}
